---
title: "Replication via R & Quarto - How Can Lower-Income Countries Collect More Taxes? The Role of Technology, Tax Agents, and Politics"
author: "Arunima Pandey"
date: "2024-10-28"
format: html
output: slidy_presentaion
---

```{r}
install.packages("knitr")
library(knitr)
```

```{r}
install.packages("quarto")
```

```{r}
install.packages("tinytex")
library(tinytex)
```

```{r}
if (!require(pacman)) install.packages("pacman")
pacman::p_load(knitr, rmarkdown, papaja)

```

```{r}
install.packages("haven")
library(haven)
```

```{r}
getwd()
```

```{r}
install.packages("ggplot2")
library(ggplot2)
```

```{r}
install.packages("dplyr")
library(dplyr)
```

```{r}
setwd("/Users/arunimapandey/dsarunima2024/Packagenew/Data/01_base/unuwider_data")
```

```{r}
data <- read_dta("/Users/arunimapandey/dsarunima2024/Packagenew/Data/01_base/unuwider_data/Figure1.dta", encoding = "latin1")
head(data)
```

```{r}
class(data)
```

```{r}
colnames(data)
```

```{r}
summary(data)
```

```{r}
country_data <- data %>% select(country)
head(country_data)
```

```{r}
dataset <- read_dta("/Users/arunimapandey/dsarunima2024/Packagenew/Data/01_base/unuwider_data/figurex.dta")
head(dataset)
```

```{r}
install.packages("readxl")
library(readxl)
```

```{r}
set2 <- read_excel("/Users/arunimapandey/dsarunima2024/Packagenew/Data/01_base/lagos_data/Lagos.xlsx")
head(set2)
```

```{r}
colnames(set2)
```

```{r}
rownames(set2)
```




```{r}
names(set2)
```

```{r}
library(ggplot2)
install.packages("ggplot2")
library(ggplot2)
```

```{r}
ggplot(set2, aes(x = Year)) +
  geom_line(aes(y = `Lagos total tax from digest in billions`), color = "black") +
  labs(title = "Tax Revenues in Lagos State, Nigeria",
       x = "Year",
       y = "Lagos total tax from digest in billions")

```
